### ISSUE TITLE
Building components: create work card

### ISSUE THREAD

**Issue by jema28** [yalla-coop/website-redesign#22]
### Create work card
This component is a small representation for a work/project that has been done and it contains the following:

1. The box wrapper:
```css
{
  padding: 35px;
  background: #020F1D; /* this color is found in utils folder */
  width: 638px; /* we should be able to fit two next to each other in one container */
}
```
2. An image:
this one should be inside of a **div** that takes the full width of the container(box wrapper)

3. Caps heading small w/medium font-weight
4. Caps heading 4
```css
{ color: #fff; /* white from utils */ }
```

**Main Props**:
- Image: Could be a URL or a stored image(preferred)
- Small Heading (caps heading small)
- Big Heading (heading 4)

This is how the component should look like when given all the props
![Work card](https://user-images.githubusercontent.com/44949822/76198378-a8333a00-61f6-11ea-8659-8482c1ccc87a.png)
