### ISSUE TITLE
Building components: quote

### ISSUE THREAD

**Issue by yosefanajjar** [yalla-coop/website-redesign#42]
### Create quote component
![Quote](https://user-images.githubusercontent.com/44949822/76455971-f9058700-63de-11ea-9305-cc79d6654a66.png)

This component should contain:
1. **Quote Sign**:
Which is just a normal quote that has the following styles:
```css
{
  font-size: 100px;
  color: #C73E46;
  font-weight: 700;

 /* and these spacings: */
  margin: 0 19px 15px 0;
}
```
2. **Heading 3**:
Which has the following styles: 
```css 
{
  color: #000000;
  margin-bottom: 50px; /* the space between it and the paragraph */
}
```

3. **Body / Extra-large (Regular)**:
Which has the following styles: 
```css
{
  color: #858585;
  margin-bottom: 8px;
}
```

4. **Caps Heading / Large (Medium)** 
Which has the following styles: 
```css 
{
  color: #000000;
  margin-bottom: 5px;
}
```
5. **Caps Heading / Medium (Bold)**
Which has the following styles: 
```css
{
  color: #C4C4C4;
}
```

And  these elements should be a representation for the following props:
- **Headline**
- **Body**
- **Name**
- **Position**
